namespace: prod

replicaCount: 2

image:
  repository: tiwarishivam/argo-helm
  tag: "32fc1e9"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  host: ""
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"