apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mygoapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiwarishivam18/argo-helm.git
    targetRevision: main
    path: gitops/helm/argo-helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true